#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-hisiv200-linux-gcc -O3"
  #define PLATFORM "arm-hisiv200-linux-gcc"
  #define DATE "Tue Nov 18 05:10:05 EST 2014"
#endif
