/* confdefs.h */
#define PACKAGE_NAME "json-c"
#define PACKAGE_TARNAME "json-c"
#define PACKAGE_VERSION "0.12.99"
#define PACKAGE_STRING "json-c 0.12.99"
#define PACKAGE_BUGREPORT "json-c@googlegroups.com"
#define PACKAGE_URL ""
#define PACKAGE "json-c"
#define VERSION "0.12.99"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FCNTL_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYSLOG_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_STDARG_H 1
#define HAVE_LOCALE_H 1
#define HAVE_ENDIAN_H 1
#define JSON_C_HAVE_INTTYPES_H 1
#define HAVE_VPRINTF 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 0
#define malloc rpl_malloc
#define HAVE_STDLIB_H 1
#define HAVE_REALLOC 0
#define realloc rpl_realloc
#define HAVE_STRCASECMP 1
#define HAVE_STRDUP 1
#define HAVE_STRERROR 1
#define HAVE_SNPRINTF 1
#define HAVE_VSNPRINTF 1
#define HAVE_VASPRINTF 1
#define HAVE_OPEN 1
#define HAVE_VSYSLOG 1
#define HAVE_STRNCASECMP 1
#define HAVE_SETLOCALE 1
#define HAVE_DECL_INFINITY 1
#define HAVE_DECL_NAN 1
#define HAVE_DECL_ISNAN 1
#define HAVE_DECL_ISINF 1
#define HAVE_DECL__ISNAN 0
#define HAVE_DECL__FINITE 0
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
